apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd-deployment
  labels:
    app: test-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cicd
  template:
    metadata:
      labels:
        app: test-cicd
    spec:
      containers:
        - name: test-cicd
          image: fr000st91/test-cicd:latest
          ports:
            - containerPort: 8090
            
---

apiVersion: v1
kind: Service
metadata:
  name: test-cicd-service
spec:
  selector:
    app: test-cicd
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 31110
